/**
 * Registro curado de íconos disponibles para los menús.
 * Agrega o quita íconos según las necesidades del proyecto.
 * Solo se incluyen en el bundle los íconos registrados aquí.
 */
import {
    Activity,
    AlarmClock,
    Archive,
    BarChart2,
    BarChart3,
    Bell,
    BookOpen,
    Boxes,
    Briefcase,
    Building2,
    Calendar,
    CalendarCheck,
    ChartPie,
    CheckCircle,
    CheckSquare,
    ChevronRight,
    ClipboardList,
    Clock,
    Cloud,
    Cog,
    CreditCard,
    DollarSign,
    FileBarChart,
    FileCheck,
    FileText,
    Folder,
    FolderOpen,
    Globe,
    Grid2x2,
    HelpCircle,
    Home,
    Image,
    Inbox,
    KeyRound,
    LayoutDashboard,
    LayoutGrid,
    LayoutList,
    Link,
    List,
    Lock,
    LogOut,
    Mail,
    Map,
    MessageCircle,
    MessageSquare,
    Monitor,
    Moon,
    Package,
    Palette,
    Pencil,
    PieChart,
    Pin,
    Plus,
    Printer,
    Receipt,
    Search,
    Send,
    Settings,
    Settings2,
    Share2,
    Shield,
    ShoppingBag,
    ShoppingCart,
    Star,
    Sun,
    Tag,
    Tags,
    Target,
    Trash2,
    TrendingDown,
    TrendingUp,
    Truck,
    User,
    UserCheck,
    UserCog,
    UserPlus,
    Users,
    Wallet,
    Wrench,
    Zap,
} from 'lucide-react';
import type { LucideProps } from 'lucide-react';
import type { ForwardRefExoticComponent, RefAttributes } from 'react';

export type LucideIcon = ForwardRefExoticComponent<LucideProps & RefAttributes<SVGSVGElement>>;

/** Mapa nombre → componente */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
    Activity,
    AlarmClock,
    Archive,
    BarChart2,
    BarChart3,
    Bell,
    BookOpen,
    Boxes,
    Briefcase,
    Building2,
    Calendar,
    CalendarCheck,
    ChartPie,
    CheckCircle,
    CheckSquare,
    ChevronRight,
    ClipboardList,
    Clock,
    Cloud,
    Cog,
    CreditCard,
    DollarSign,
    FileBarChart,
    FileCheck,
    FileText,
    Folder,
    FolderOpen,
    Globe,
    Grid2x2,
    HelpCircle,
    Home,
    Image,
    Inbox,
    KeyRound,
    LayoutDashboard,
    LayoutGrid,
    LayoutList,
    Link,
    List,
    Lock,
    LogOut,
    Mail,
    Map,
    MessageCircle,
    MessageSquare,
    Monitor,
    Moon,
    Package,
    Palette,
    Pencil,
    PieChart,
    Pin,
    Plus,
    Printer,
    Receipt,
    Search,
    Send,
    Settings,
    Settings2,
    Share2,
    Shield,
    ShoppingBag,
    ShoppingCart,
    Star,
    Sun,
    Tag,
    Tags,
    Target,
    Trash2,
    TrendingDown,
    TrendingUp,
    Truck,
    User,
    UserCheck,
    UserCog,
    UserPlus,
    Users,
    Wallet,
    Wrench,
    Zap,
};

/** Lista ordenada para el picker */
export const ICON_LIST = Object.keys(ICON_REGISTRY).sort();

/** Renderiza un ícono por nombre. Retorna null si no existe. */
export function DynamicIcon({
    name,
    className,
    size,
}: {
    name: string | null | undefined;
    className?: string;
    size?: number;
}) {
    if (!name) return null;
    const Icon = ICON_REGISTRY[name];
    if (!Icon) return null;
    return <Icon className={className} size={size} />;
}
